server:
  port : 5001
  
# ==============================================================
# = Propriet√† Livello Log
# = Default ERROR, WARN e INFO 
# = Levels: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
# ============================================================== 

logging:
  file:
    name: mediaw.log
    max-size: 1MB
  pattern:
    file: "%d{ dd-MM-yyyy } [%thread] %-5level %logger{36} - %msg%n"
    #console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    
  # Livello del Log generale
  level:
   root: INFO
